version: '3.7'
services:
    workspace:
        build:
            context: ./workspace
            args:
                - PHP_VERSION=7.4
        image: global_workspace:latest
        volumes:
            - ../:/var/htdocs
        tty: true
    
    workspace-8:
        build:
            context: ./workspace-8
            args:
                - PHP_VERSION=8.0.0RC3
        image: global_8_workspace:latest
        volumes:
            - ../:/var/htdocs
        tty: true
